### ISSUE TITLE
delete option is not working in action part of "Category" in phpbb 3.2.1

### ISSUE THREAD

**Issue by tejaskp114** [GerB/cmbb#10]
thanks for creating a wonderful blog. delete option is not working in action part of "Category" in phpbb 3.2.1 even though there are no children.

Registered users are not able to create new posts/articles.

**Comment by GerB** [comment]
Thanks for mentioning, fixed just now.

Your other question is a matter of permission, see https://www.phpbb.com/community/viewtopic.php?f=456&t=2383541&p=14889176#p14889176
