### ISSUE TITLE
Not able to upload any of the allowed file types. Its not reflected in the article.

### ISSUE THREAD

**Issue by tejaskp114** [GerB/cmbb#11]
Thanks.I assigned the permission "Can post cmBB articles" to the "Registered users" group as "yes" but still the users in that group are not able to create new post/article.

Also not able to upload any of the allowed file types. Its not reflected in the article.

**Comment by GerB** [comment]
https://www.phpbb.com/community/viewtopic.php?f=456&t=2383541&p=14890181#p14890181
