### ISSUE TITLE
SQL ERROR [ postgres 11 ] ERROR: LIMIT #,# syntax is not supported

### ISSUE THREAD

**Issue by ekaterina-git** [GerB/cmbb#13]
While creating a new article, I received an error:

```
SQL ERROR [ postgres ]
 
ERROR: LIMIT #,# syntax is not supported LINE 7: LIMIT 0,5 ^ HINT: Use separate LIMIT and OFFSET clauses. []
 
SQL

SELECT t.topic_id, t.forum_id, t.topic_title FROM phpbb_topics t , phpbb_users u WHERE topic_visibility = 1 AND forum_id IN (1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31) AND u.user_id = t.topic_poster ORDER BY topic_time DESC LIMIT 0,5

```
I fixed it by using `sql_query_limit` in `\ger\cmbb\cmbb\driver::phpbb_latest_topics` . Should I create a PR?

**Comment by GerB** [comment]
Funny, I'd expected the validation team to check for such compatibility stuff through supported dbms's. I haven't ever used Postgres so never noticed id. You're probably the first Postgres user for cmBB ;)

If you like, please create a PR, I really appreciate it.

**Comment by ekaterina-git** [comment]
But they actually did, it's just you used plain "limit" in SQL :) They introduced a method `sql_query_limit` which accepts query without "limit" and makes it compatible for different databases.
I you can probably except more issues from me then :) Okay, I will create a PR.
