### ISSUE TITLE
SQL ERROR [ postgres 11 ] ERROR: column "0" does not exist 

### ISSUE THREAD

**Issue by ekaterina-git** [GerB/cmbb#14]
While creating a new article, I received an error:

```
SQL ERROR [ postgres ]

ERROR: column "0" does not exist LINE 1: ...mbb_category WHERE std_parent > 1 AND protected = "0" ORDER... ^ []

SQL

SELECT * FROM phpbb_cmbb_category WHERE std_parent > 1 AND protected = "0" ORDER BY category_name ASC
```

I fixed it by replacing 
`$query .= ' AND protected = "' . CMBB_FALSE . '" ';`
with 
`$query .= ' AND protected = ' . CMBB_FALSE . ' ';`
in `\ger\cmbb\cmbb\driver::get_categories` though I'm not sure it still leaves this compatible with MySQL

**Comment by GerB** [comment]
Probably another Postgres compatibility issue. Using the later created constant should work throughout all DBMS's, would you like to add this to your PR? 

Could you check any other Postgres issues as well? I'm not having a lot of time at the moment with a newborn son... 

Thanks!

**Comment by ekaterina-git** [comment]
Yes, sure, congratulations on a newborn :)
I cannot guarantee that I will be looking for other Postgres bugs, but if I encounter something accidentally, of course I will try and fix it.

**Comment by GerB** [comment]
Thanks! :)
